### ISSUE TITLE
Could not load fonts.

### ISSUE THREAD

**Issue by 2tvenom** [BenNicholls/spaceshippers#1]
Cant start game. Got "Could not load fonts."

All deps installed. Mac OS X 10.13.3, go version go1.8.3 darwin/amd64

**Comment by BenNicholls** [comment]
Hello! 

The game is looking for the fonts in the "res" folder, specifically "res/curses24x24.bmp" and "res/DelveFont12x24.bmp". The game needs to be run from the folder containing the "res" folder. Not knowing that what your setup looks like, I suspect you'll have to navigate to GOROOT/src/github.com/bennicholls/spaceshippers and put the executable there along with the code.

Let me know if you can get it working. More robust messaging about these sorts of errors is clearly needed. Thanks!

**Comment by 2tvenom** [comment]
yep, got it! thx
